stages:
  - infraonly
  - minimal
  - basic
  - small
  - medium
  - full


.docker-build:
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"


.latest-build:
  extends: .docker-build
  rules:
    - if: $TEXLIVE_YEAR
    - if: $TEXLIVE_MODE == "latest"


.archived-build:
  extends: .docker-build
  rules:
    - if: $TEXLIVE_YEAR
    - if: $TEXLIVE_MODE == "archive"


texlive-infraonly-latest:
  extends: .latest-build
  stage: infraonly
  script:
    - docker build
      --pull
      --tag "$CI_REGISTRY_IMAGE:$TEXLIVE_YEAR-infraonly"
      --tag "$CI_REGISTRY_IMAGE:latest-infraonly"
      --file infraonly/Dockerfile
      infraonly/
    - docker push "$CI_REGISTRY_IMAGE:$TEXLIVE_YEAR-infraonly"
    - docker push "$CI_REGISTRY_IMAGE:latest-infraonly"


texlive-minimal-latest:
  extends: .latest-build
  stage: minimal
  script:
    - docker build
      --tag "$CI_REGISTRY_IMAGE:$TEXLIVE_YEAR-minimal"
      --tag "$CI_REGISTRY_IMAGE:latest-minimal"
      --file minimal/Dockerfile
      minimal/
    - docker push "$CI_REGISTRY_IMAGE:$TEXLIVE_YEAR-minimal"
    - docker push "$CI_REGISTRY_IMAGE:latest-minimal"


texlive-basic-latest:
  extends: .latest-build
  stage: basic
  script:
    - docker build
      --tag "$CI_REGISTRY_IMAGE:$TEXLIVE_YEAR-basic"
      --tag "$CI_REGISTRY_IMAGE:latest-basic"
      --file basic/Dockerfile
      basic/
    - docker push "$CI_REGISTRY_IMAGE:$TEXLIVE_YEAR-basic"
    - docker push "$CI_REGISTRY_IMAGE:latest-basic"


texlive-small-latest:
  extends: .latest-build
  stage: small
  script:
    - docker build
      --tag "$CI_REGISTRY_IMAGE:$TEXLIVE_YEAR-small"
      --tag "$CI_REGISTRY_IMAGE:latest-small"
      --file small/Dockerfile
      small/
    - docker push "$CI_REGISTRY_IMAGE:$TEXLIVE_YEAR-small"
    - docker push "$CI_REGISTRY_IMAGE:latest-small"


texlive-medium-latest:
  extends: .latest-build
  stage: medium
  script:
    - docker build
      --tag "$CI_REGISTRY_IMAGE:$TEXLIVE_YEAR-medium"
      --tag "$CI_REGISTRY_IMAGE:latest-medium"
      --tag "$CI_REGISTRY_IMAGE:latest"
      --file medium/Dockerfile
      medium/
    - docker push "$CI_REGISTRY_IMAGE:$TEXLIVE_YEAR-medium"
    - docker push "$CI_REGISTRY_IMAGE:latest-medium"


texlive-full-latest:
  extends: .latest-build
  stage: full
  script:
    - docker build
      --tag "$CI_REGISTRY_IMAGE:$TEXLIVE_YEAR-full"
      --tag "$CI_REGISTRY_IMAGE:latest-full"
      --file full/Dockerfile
      full/
    - docker push "$CI_REGISTRY_IMAGE:$TEXLIVE_YEAR-full"
    - docker push "$CI_REGISTRY_IMAGE:latest-full"


texlive-infraonly-archived:
  extends: .archived-build
  stage: infraonly
  script:
    - docker build
      --tag "$CI_REGISTRY_IMAGE:$TEXLIVE_YEAR-infraonly"
      --file $TEXLIVE_YEAR/infraonly/Dockerfile
      $TEXLIVE_YEAR/infraonly/
    - docker push "$CI_REGISTRY_IMAGE:$TEXLIVE_YEAR-infraonly"


texlive-minimal-archived:
  extends: .archived-build
  stage: minimal
  script:
    - docker build
      --tag "$CI_REGISTRY_IMAGE:$TEXLIVE_YEAR-minimal"
      --file $TEXLIVE_YEAR/minimal/Dockerfile
      $TEXLIVE_YEAR/minimal/
    - docker push "$CI_REGISTRY_IMAGE:$TEXLIVE_YEAR-minimal"


texlive-basic-archived:
  extends: .archived-build
  stage: basic
  script:
    - docker build
      --tag "$CI_REGISTRY_IMAGE:$TEXLIVE_YEAR-basic"
      --file $TEXLIVE_YEAR/basic/Dockerfile
      $TEXLIVE_YEAR/basic/
    - docker push "$CI_REGISTRY_IMAGE:$TEXLIVE_YEAR-basic"


texlive-small-archived:
  extends: .archived-build
  stage: small
  script:
    - docker build
      --tag "$CI_REGISTRY_IMAGE:$TEXLIVE_YEAR-small"
      --file $TEXLIVE_YEAR/small/Dockerfile
      $TEXLIVE_YEAR/small/
    - docker push "$CI_REGISTRY_IMAGE:$TEXLIVE_YEAR-small"


texlive-medium-archived:
  extends: .archived-build
  stage: medium
  script:
    - docker build
      --tag "$CI_REGISTRY_IMAGE:$TEXLIVE_YEAR-medium"
      --file $TEXLIVE_YEAR/medium/Dockerfile
      $TEXLIVE_YEAR/medium/
    - docker push "$CI_REGISTRY_IMAGE:$TEXLIVE_YEAR-medium"


texlive-full-archived:
  extends: .archived-build
  stage: full
  script:
    - docker build
      --tag "$CI_REGISTRY_IMAGE:$TEXLIVE_YEAR-full"
      --tag "$CI_REGISTRY_IMAGE:$TEXLIVE_YEAR"
      --file $TEXLIVE_YEAR/full/Dockerfile
      $TEXLIVE_YEAR/full/
    - docker push "$CI_REGISTRY_IMAGE:$TEXLIVE_YEAR-full"
