stages:
  - ubuntu
  - infraonly
  - minimal
  - basic
  - small
  - medium
  - full


.docker:
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - source src/constants.sh
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - docker login -u "$DOCKER_REGISTRY_USER" -p "$DOCKER_REGISTRY_PASSWORD" "$DOCKER_REGISTRY"


texlive:ubuntu:
  extends: .docker
  stage: ubuntu
  script:
    - TEXLIVE_REPO="${TEXLIVE_REPO}" UBUNTU_FLAVOR="${UBUNTU_FLAVOR}" TEXLIVE_YEAR="${TEXLIVE_YEAR}" src/maker.sh build "ubuntu"
    - TEXLIVE_YEAR="${TEXLIVE_YEAR}" src/maker.sh push "ubuntu"


texlive:infraonly:
  extends: .docker
  stage: infraonly
  needs:
    - texlive:ubuntu
  script:
    - TEXLIVE_REPO="${TEXLIVE_REPO}" UBUNTU_FLAVOR="${UBUNTU_FLAVOR}" TEXLIVE_YEAR="${TEXLIVE_YEAR}" src/maker.sh build "infraonly"
    - TEXLIVE_YEAR="${TEXLIVE_YEAR}" src/maker.sh push "infraonly"


texlive:minimal:
  extends: .docker
  stage: minimal
  needs:
    - texlive:infraonly
  script:
    - TEXLIVE_REPO="${TEXLIVE_REPO}" UBUNTU_FLAVOR="${UBUNTU_FLAVOR}" TEXLIVE_YEAR="${TEXLIVE_YEAR}" src/maker.sh build "minimal"
    - TEXLIVE_YEAR="${TEXLIVE_YEAR}" src/maker.sh push "minimal"


texlive:basic:
  extends: .docker
  stage: basic
  needs:
    - texlive:minimal
  script:
    - TEXLIVE_REPO="${TEXLIVE_REPO}" UBUNTU_FLAVOR="${UBUNTU_FLAVOR}" TEXLIVE_YEAR="${TEXLIVE_YEAR}" src/maker.sh build "basic"
    - TEXLIVE_YEAR="${TEXLIVE_YEAR}" src/maker.sh push "basic"


texlive:small:
  extends: .docker
  stage: small
  needs:
    - texlive:basic
  script:
    - TEXLIVE_REPO="${TEXLIVE_REPO}" UBUNTU_FLAVOR="${UBUNTU_FLAVOR}" TEXLIVE_YEAR="${TEXLIVE_YEAR}" src/maker.sh build "small"
    - TEXLIVE_YEAR="${TEXLIVE_YEAR}" src/maker.sh push "small"


texlive:medium:
  extends: .docker
  stage: medium
  needs:
    - texlive:small
  script:
    - TEXLIVE_REPO="${TEXLIVE_REPO}" UBUNTU_FLAVOR="${UBUNTU_FLAVOR}" TEXLIVE_YEAR="${TEXLIVE_YEAR}" src/maker.sh build "medium"
    - TEXLIVE_YEAR="${TEXLIVE_YEAR}" src/maker.sh push "medium"


texlive:full:
  extends: .docker
  stage: full
  needs:
    - texlive:medium
  script:
    - TEXLIVE_REPO="${TEXLIVE_REPO}" UBUNTU_FLAVOR="${UBUNTU_FLAVOR}" TEXLIVE_YEAR="${TEXLIVE_YEAR}" src/maker.sh build "full"
    - TEXLIVE_YEAR="${TEXLIVE_YEAR}" src/maker.sh push "full"
