stages:
  - ubuntu
  - infraonly
  - minimal
  - basic
  - small
  - medium
  - full


.docker-build:
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - docker login -u "$DOCKER_REGISTRY_USER" -p "$DOCKER_REGISTRY_PASSWORD" "$DOCKER_REGISTRY"


texlive:ubuntu:
  extends: .docker-build
  stage: ubuntu
  script:
    - ./src/maker.sh build "$TEXLIVE_YEAR" "ubuntu"
    - ./src/maker.sh push "$TEXLIVE_YEAR" "ubuntu"


texlive:infraonly:
  extends: .docker-build
  stage: infraonly
  script:
    - ./src/maker.sh build "$TEXLIVE_YEAR" "infraonly"
    - ./src/maker.sh push "$TEXLIVE_YEAR" "infraonly"


texlive:minimal:
  extends: .docker-build
  stage: minimal
  needs: infraonly
  script:
    - ./src/maker.sh build "$TEXLIVE_YEAR" "minimal"
    - ./src/maker.sh push "$TEXLIVE_YEAR" "minimal"


texlive:basic:
  extends: .docker-build
  stage: basic
  needs: minimal
  script:
    - ./src/maker.sh build "$TEXLIVE_YEAR" "basic"
    - ./src/maker.sh push "$TEXLIVE_YEAR" "basic"


texlive:small:
  extends: .docker-build
  stage: small
  needs: basic
  script:
    - ./src/maker.sh build "$TEXLIVE_YEAR" "small"
    - ./src/maker.sh push "$TEXLIVE_YEAR" "small"


texlive:medium:
  extends: .docker-build
  stage: medium
  needs: small
  script:
    - ./src/maker.sh build "$TEXLIVE_YEAR" "medium"
    - ./src/maker.sh push "$TEXLIVE_YEAR" "medium"


texlive:full:
  extends: .docker-build
  stage: full
  needs: medium
  script:
    - ./src/maker.sh build "$TEXLIVE_YEAR" "full"
    - ./src/maker.sh push "$TEXLIVE_YEAR" "full"
