stages:
  - infraonly
  - minimal
  - basic
  - small
  - medium
  - full


.docker-build:
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"


.latest-build:
  extends: .docker-build
  rules:
    - if: '$CI_COMMIT_BRANCH == "latest"'
      changes:
        - ./*/Dockerfile
        - ./.gitlab-ci.yml


.archived-build:
  extends: .docker-build
  rules:
    - if: '$CI_COMMIT_TAG'
      changes:
        - ./*/Dockerfile
        - ./.gitlab-ci.yml


texlive-infraonly-latest:
  extends: .latest-build
  stage: infraonly
  script:
    - docker build --pull --tag "$CI_REGISTRY_IMAGE:latest-infraonly" --tag "$CI_REGISTRY_IMAGE:$CI_TEXLIVE_YEAR-infraonly" --file infraonly/Dockerfile infraonly/
    - docker push "$CI_REGISTRY_IMAGE:latest-infraonly"
    - docker push "$CI_REGISTRY_IMAGE:$CI_TEXLIVE_YEAR-infraonly"


texlive-minimal-latest:
  extends: .latest-build
  stage: minimal
  script:
    - docker build --pull --tag "$CI_REGISTRY_IMAGE:latest-minimal"  --tag "$CI_REGISTRY_IMAGE:$CI_TEXLIVE_YEAR-minimal" --file minimal/Dockerfile minimal/
    - docker push "$CI_REGISTRY_IMAGE:latest-minimal"
    - docker push "$CI_REGISTRY_IMAGE:$CI_TEXLIVE_YEAR-minimal"


texlive-basic-latest:
  extends: .latest-build
  stage: basic
  script:
    - docker build --pull --tag "$CI_REGISTRY_IMAGE:latest-basic"  --tag "$CI_REGISTRY_IMAGE:$CI_TEXLIVE_YEAR-basic" --file basic/Dockerfile basic/
    - docker push "$CI_REGISTRY_IMAGE:latest-basic"
    - docker push "$CI_REGISTRY_IMAGE:$CI_TEXLIVE_YEAR-basic"


texlive-small-latest:
  extends: .latest-build
  stage: small
  script:
    - docker build --pull --tag "$CI_REGISTRY_IMAGE:latest-small"  --tag "$CI_REGISTRY_IMAGE:$CI_TEXLIVE_YEAR-small" --file small/Dockerfile small/
    - docker push "$CI_REGISTRY_IMAGE:latest-small"
    - docker push "$CI_REGISTRY_IMAGE:$CI_TEXLIVE_YEAR-small"


texlive-medium-latest:
  extends: .latest-build
  stage: medium
  script:
    - docker build --pull --tag "$CI_REGISTRY_IMAGE:latest-medium"  --tag "$CI_REGISTRY_IMAGE:$CI_TEXLIVE_YEAR-medium" --tag "$CI_REGISTRY_IMAGE:latest" --file medium/Dockerfile medium/
    - docker push "$CI_REGISTRY_IMAGE:latest-medium"
    - docker push "$CI_REGISTRY_IMAGE:$CI_TEXLIVE_YEAR-medium"


texlive-full-latest:
  extends: .latest-build
  stage: full
  script:
    - docker build --pull --tag "$CI_REGISTRY_IMAGE:latest-full"  --tag "$CI_REGISTRY_IMAGE:$CI_TEXLIVE_YEAR-full" --file full/Dockerfile full/
    - docker push "$CI_REGISTRY_IMAGE:latest-full"
    - docker push "$CI_REGISTRY_IMAGE:$CI_TEXLIVE_YEAR-full"


texlive-infraonly-archived:
  extends: .archived-build
  stage: infraonly
  script:
    - docker build --pull --tag "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-infraonly" --file infraonly/Dockerfile infraonly/
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-infraonly"


texlive-minimal-archived:
  extends: .archived-build
  stage: minimal
  script:
    - docker build --pull --tag "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-minimal" --file minimal/Dockerfile minimal/
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-minimal"


texlive-basic-archived:
  extends: .archived-build
  stage: basic
  script:
    - docker build --pull --tag "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-basic" --file basic/Dockerfile basic/
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-basic"


texlive-small-archived:
  extends: .archived-build
  stage: small
  script:
    - docker build --pull --tag "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-small" --file small/Dockerfile small/
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-small"


texlive-medium-archived:
  extends: .archived-build
  stage: medium
  script:
    - docker build --pull --tag "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-medium" --file medium/Dockerfile medium/
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-medium"


texlive-full-archived:
  extends: .archived-build
  stage: full
  script:
    - docker build --pull --tag "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-full" --tag "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" --file full/Dockerfile full/
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-full"
